Repository junghojune/sparta-project1, pull requests merged in 2024-08, with the labels that each got.

#3 Docs : READMD.md 작성
  README.md
Labels: documentation

#5 README.md 작성
  README.md
Labels: enhancement

#10 Feat : Store, Menu 엔티티 작성, Jpa Auditing 관련 클래스 작성 및 설정
  README.md
  src/main/java/com/sparta/project/delivery/common/BaseEntity.java
  src/main/java/com/sparta/project/delivery/common/config/JpaConfig.java
  src/main/java/com/sparta/project/delivery/menu/Menu.java
  src/main/java/com/sparta/project/delivery/store/Store.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#20 Feat : 주문 엔티티 작성
  src/main/java/com/sparta/project/delivery/order/Order.java
Labels: enhancement

#21 Feat : ai 엔티티
  src/main/java/com/sparta/project/delivery/ai/Ai.java
Labels: enhancement

#22 Feat : region 엔티티
  src/main/java/com/sparta/project/delivery/region/Region.java
Labels: enhancement

#23 Feat : category 엔티티
  src/main/java/com/sparta/project/delivery/category/Category.java
Labels: enhancement

#26 Feat : Address 엔티티
  src/main/java/com/sparta/project/delivery/address/Address.java
  src/main/java/com/sparta/project/delivery/common/Order.java
Labels: enhancement

#28 Feat : 엔티티 수정 및 연관관계 설정
  src/main/java/com/sparta/projcet/delivery/user/User.java
  src/main/java/com/sparta/project/delivery/address/Address.java
  src/main/java/com/sparta/project/delivery/ai/Ai.java
  src/main/java/com/sparta/project/delivery/category/Category.java
  src/main/java/com/sparta/project/delivery/common/type/City.java
  src/main/java/com/sparta/project/delivery/common/type/DeliveryType.java
  src/main/java/com/sparta/project/delivery/common/type/OrderStatus.java
  src/main/java/com/sparta/project/delivery/common/type/UserRoleEnum.java
  src/main/java/com/sparta/project/delivery/order/Order.java
  src/main/java/com/sparta/project/delivery/order/OrderMenu.java
  src/main/java/com/sparta/project/delivery/region/Region.java
  src/main/java/com/sparta/project/delivery/store/Store.java
  src/main/java/com/sparta/project/delivery/user/User.java
Labels: enhancement

#34 Feat : category api 개발
  src/main/java/com/sparta/project/delivery/category/Category.java
  src/main/java/com/sparta/project/delivery/category/CategoryController.java
  src/main/java/com/sparta/project/delivery/category/controller/CategoryController.java
  src/main/java/com/sparta/project/delivery/category/dto/CategoryDto.java
  src/main/java/com/sparta/project/delivery/category/dto/CategoryRequest.java
  src/main/java/com/sparta/project/delivery/category/dto/CategoryResponse.java
  src/main/java/com/sparta/project/delivery/category/entity/Category.java
  src/main/java/com/sparta/project/delivery/category/repository/CategoryRepository.java
  src/main/java/com/sparta/project/delivery/category/service/CategoryService.java
  src/main/java/com/sparta/project/delivery/common/BaseEntity.java
  src/main/java/com/sparta/project/delivery/store/Store.java
Labels: enhancement

#38 Feat: Store api 1차 작성
  build.gradle
  src/main/java/com/sparta/project/delivery/common/BaseEntity.java
  src/main/java/com/sparta/project/delivery/common/config/JpaConfig.java
  src/main/java/com/sparta/project/delivery/store/controller/StoreController.java
  src/main/java/com/sparta/project/delivery/store/dto/StoreDto.java
  src/main/java/com/sparta/project/delivery/store/dto/request/CreateStore.java
  src/main/java/com/sparta/project/delivery/store/dto/request/UpdateStore.java
  src/main/java/com/sparta/project/delivery/store/dto/response/StoreResponse.java
  src/main/java/com/sparta/project/delivery/store/entity/Store.java
  src/main/java/com/sparta/project/delivery/store/repository/StoreRepository.java
  src/main/java/com/sparta/project/delivery/store/service/StoreService.java
  src/test/resources/application.yml
Labels: enhancement

#41 Feat : region api 개발
  src/main/java/com/sparta/project/delivery/menu/Menu.java
  src/main/java/com/sparta/project/delivery/order/Order.java
  src/main/java/com/sparta/project/delivery/region/Region.java
  src/main/java/com/sparta/project/delivery/region/controller/RegionController.java
  src/main/java/com/sparta/project/delivery/region/dto/RegionDto.java
  src/main/java/com/sparta/project/delivery/region/dto/RegionRequest.java
  src/main/java/com/sparta/project/delivery/region/dto/RegionResponse.java
  src/main/java/com/sparta/project/delivery/region/entity/Region.java
  src/main/java/com/sparta/project/delivery/region/repository/RegionRepository.java
  src/main/java/com/sparta/project/delivery/region/service/RegionService.java
  src/main/java/com/sparta/project/delivery/store/entity/Store.java
Labels: enhancement

#42 Feat : Menu API 1차 작성
  src/main/java/com/sparta/project/delivery/menu/controller/MenuController.java
  src/main/java/com/sparta/project/delivery/menu/dto/MenuDto.java
  src/main/java/com/sparta/project/delivery/menu/dto/request/CreateMenu.java
  src/main/java/com/sparta/project/delivery/menu/dto/request/UpdateMenu.java
  src/main/java/com/sparta/project/delivery/menu/dto/response/MenuResponse.java
  src/main/java/com/sparta/project/delivery/menu/entity/Menu.java
  src/main/java/com/sparta/project/delivery/menu/repository/MenuRepository.java
  src/main/java/com/sparta/project/delivery/menu/service/MenuService.java
  src/main/java/com/sparta/project/delivery/order/Order.java
  src/main/java/com/sparta/project/delivery/order/OrderMenu.java
  src/main/java/com/sparta/project/delivery/store/dto/StoreDto.java
  src/main/java/com/sparta/project/delivery/store/dto/response/StoreResponse.java
  src/main/java/com/sparta/project/delivery/store/repository/StoreRepository.java
  src/main/java/com/sparta/project/delivery/store/service/StoreService.java
Labels: enhancement

#44 Feat : AI api 개발
  src/main/java/com/sparta/project/delivery/ai/Ai.java
  src/main/java/com/sparta/project/delivery/ai/Entity/Ai.java
  src/main/java/com/sparta/project/delivery/ai/config/GeminiInterface.java
  src/main/java/com/sparta/project/delivery/ai/config/GeminiRestTemplateConfig.java
  src/main/java/com/sparta/project/delivery/ai/controller/AiController.java
  src/main/java/com/sparta/project/delivery/ai/dto/AiDto.java
  src/main/java/com/sparta/project/delivery/ai/dto/AiRequest.java
  src/main/java/com/sparta/project/delivery/ai/dto/AiResponse.java
  src/main/java/com/sparta/project/delivery/ai/dto/GeminiRequest.java
  src/main/java/com/sparta/project/delivery/ai/dto/GeminiResponse.java
  src/main/java/com/sparta/project/delivery/ai/repository/AiRepository.java
  src/main/java/com/sparta/project/delivery/ai/service/GeminiService.java
  src/main/resources/application.yml
Labels: enhancement

#47 Feat : 리뷰 도메인 정의 및 엔티티 작성
  src/main/java/com/sparta/project/delivery/review/entity/Review.java
  src/main/java/com/sparta/project/delivery/store/dto/StoreDto.java
  src/main/java/com/sparta/project/delivery/store/entity/Store.java
Labels: documentation, enhancement

#49 Feat : 공지사항 & 고객센터 신고 테이블 정의, 엔티티 작성
  src/main/java/com/sparta/project/delivery/inquiry/entity/Inquiry.java
  src/main/java/com/sparta/project/delivery/notice/entity/Notice.java
Labels: documentation, enhancement

#50 Feat : order API 개발
  src/main/java/com/sparta/project/delivery/common/type/OrderStatus.java
  src/main/java/com/sparta/project/delivery/order/OrderMenu.java
  src/main/java/com/sparta/project/delivery/order/controller/OrderController.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderDto.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderMenuDto.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderMenuRequest.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderMenuResponse.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderRequest.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderResponse.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderWithMenuDto.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderWithMenuResponse.java
  src/main/java/com/sparta/project/delivery/order/entity/Order.java
  src/main/java/com/sparta/project/delivery/order/entity/OrderMenu.java
  src/main/java/com/sparta/project/delivery/order/repository/OrderMenuRepository.java
  src/main/java/com/sparta/project/delivery/order/repository/OrderRepository.java
  src/main/java/com/sparta/project/delivery/order/service/OrderService.java
Labels: enhancement

#55 Feat - RDS 연결
  .gitignore
  build.gradle
  src/main/java/com/sparta/project/delivery/review/entity/Review.java
  src/main/java/com/sparta/project/delivery/store/entity/Store.java
  src/main/resources/application.yml
Labels: enhancement

#54 Feat : 공지사항 API 작성, Chore : queryDSL 의존성 추가
  build.gradle
  src/main/java/com/sparta/project/delivery/notice/constant/NoticeSearchType.java
  src/main/java/com/sparta/project/delivery/notice/controller/NoticeController.java
  src/main/java/com/sparta/project/delivery/notice/dto/NoticeDto.java
  src/main/java/com/sparta/project/delivery/notice/dto/NoticeRequest.java
  src/main/java/com/sparta/project/delivery/notice/dto/NoticeResponse.java
  src/main/java/com/sparta/project/delivery/notice/repository/NoticeRepository.java
  src/main/java/com/sparta/project/delivery/notice/service/NoticeService.java
Labels: enhancement

#58 Feat : 고객센터 신고 API 작성
  src/main/java/com/sparta/project/delivery/inquiry/constant/InquirySearchType.java
  src/main/java/com/sparta/project/delivery/inquiry/constant/InquiryStatus.java
  src/main/java/com/sparta/project/delivery/inquiry/controller/InquiryController.java
  src/main/java/com/sparta/project/delivery/inquiry/dto/InquiryDto.java
  src/main/java/com/sparta/project/delivery/inquiry/dto/InquiryRequest.java
  src/main/java/com/sparta/project/delivery/inquiry/dto/InquiryResponse.java
  src/main/java/com/sparta/project/delivery/inquiry/dto/InquirySetReplyRequest.java
  src/main/java/com/sparta/project/delivery/inquiry/entity/Inquiry.java
  src/main/java/com/sparta/project/delivery/inquiry/repository/InquiryRepository.java
  src/main/java/com/sparta/project/delivery/inquiry/service/InquiryService.java
Labels: enhancement

#60 Feat : review api 개발
  src/main/java/com/sparta/project/delivery/review/controller/ReviewController.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewDto.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewReportDto.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewReportRequest.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewRequest.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewResponse.java
  src/main/java/com/sparta/project/delivery/review/entity/Review.java
  src/main/java/com/sparta/project/delivery/review/entity/ReviewReport.java
  src/main/java/com/sparta/project/delivery/review/repository/ReviewReportRepository.java
  src/main/java/com/sparta/project/delivery/review/repository/ReviewRepository.java
  src/main/java/com/sparta/project/delivery/review/service/ReviewService.java
Labels: enhancement

#61 Feat : 사용자 API 개발
  src/main/java/com/sparta/project/delivery/auth/JwtAuthenticationFilter.java
  src/main/java/com/sparta/project/delivery/auth/JwtAuthorizationFilter.java
  src/main/java/com/sparta/project/delivery/auth/JwtUtil.java
  src/main/java/com/sparta/project/delivery/auth/UserDetailsImpl.java
  src/main/java/com/sparta/project/delivery/auth/UserDetailsServiceImpl.java
  src/main/java/com/sparta/project/delivery/auth/WebSecurityConfig.java
  src/main/java/com/sparta/project/delivery/user/User.java
  src/main/java/com/sparta/project/delivery/user/controller/UserController.java
  src/main/java/com/sparta/project/delivery/user/dto/UserDto.java
  src/main/java/com/sparta/project/delivery/user/dto/request/DeleteUser.java
  src/main/java/com/sparta/project/delivery/user/dto/request/LoginRequest.java
  src/main/java/com/sparta/project/delivery/user/dto/request/SignupRequest.java
  src/main/java/com/sparta/project/delivery/user/dto/request/UpdateUser.java
  src/main/java/com/sparta/project/delivery/user/repository/UserRepository.java
  src/main/java/com/sparta/project/delivery/user/service/UserService.java
Labels: enhancement

#62 Feat : 에러 내용 정의, 글로벌 예외 핸들러 작성
  src/main/java/com/sparta/project/delivery/common/exception/ApiErrorResponse.java
  src/main/java/com/sparta/project/delivery/common/exception/CustomException.java
  src/main/java/com/sparta/project/delivery/common/exception/DeliveryError.java
  src/main/java/com/sparta/project/delivery/common/exception/GlobalExceptionHandler.java
Labels: enhancement

#64 Feat : Store API 수정
  build.gradle
  src/main/java/com/sparta/project/delivery/common/config/QueryDslConfig.java
  src/main/java/com/sparta/project/delivery/common/exception/ApiErrorResponse.java
  src/main/java/com/sparta/project/delivery/common/exception/DeliveryError.java
  src/main/java/com/sparta/project/delivery/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/project/delivery/common/response/CommonResponse.java
  src/main/java/com/sparta/project/delivery/store/constant/StoreSearchType.java
  src/main/java/com/sparta/project/delivery/store/controller/StoreController.java
  src/main/java/com/sparta/project/delivery/store/dto/StoreDto.java
  src/main/java/com/sparta/project/delivery/store/dto/request/CreateStore.java
  src/main/java/com/sparta/project/delivery/store/dto/request/UpdateStore.java
  src/main/java/com/sparta/project/delivery/store/dto/response/StoreResponse.java
  src/main/java/com/sparta/project/delivery/store/entity/Store.java
  src/main/java/com/sparta/project/delivery/store/repository/StoreRepository.java
  src/main/java/com/sparta/project/delivery/store/repository/StoreRepositoryCustom.java
  src/main/java/com/sparta/project/delivery/store/repository/StoreRepositoryCustomImpl.java
  src/main/java/com/sparta/project/delivery/store/service/StoreService.java
Labels: enhancement

#66 Fix : 공지사항, 고객센터 신고 API 수정
  src/main/java/com/sparta/project/delivery/inquiry/controller/InquiryController.java
  src/main/java/com/sparta/project/delivery/inquiry/dto/InquiryRequest.java
  src/main/java/com/sparta/project/delivery/inquiry/dto/InquirySetReplyRequest.java
  src/main/java/com/sparta/project/delivery/inquiry/entity/Inquiry.java
  src/main/java/com/sparta/project/delivery/inquiry/repository/InquiryRepository.java
  src/main/java/com/sparta/project/delivery/inquiry/repository/InquiryRepositoryCustom.java
  src/main/java/com/sparta/project/delivery/inquiry/repository/InquiryRepositoryCustomImpl.java
  src/main/java/com/sparta/project/delivery/inquiry/service/InquiryService.java
  src/main/java/com/sparta/project/delivery/notice/controller/NoticeController.java
  src/main/java/com/sparta/project/delivery/notice/dto/NoticeRequest.java
  src/main/java/com/sparta/project/delivery/notice/entity/Notice.java
  src/main/java/com/sparta/project/delivery/notice/service/NoticeService.java
Labels: enhancement

#68 Fix : api 문서(swagger) 작성, user 권한 , validation 체크 라인 정리
  src/main/java/com/sparta/project/delivery/ai/Entity/Ai.java
  src/main/java/com/sparta/project/delivery/ai/config/GeminiInterface.java
  src/main/java/com/sparta/project/delivery/ai/config/GeminiRestTemplateConfig.java
  src/main/java/com/sparta/project/delivery/ai/controller/AiController.java
  src/main/java/com/sparta/project/delivery/ai/dto/AiDto.java
  src/main/java/com/sparta/project/delivery/ai/dto/AiRequest.java
  src/main/java/com/sparta/project/delivery/ai/dto/AiResponse.java
  src/main/java/com/sparta/project/delivery/ai/dto/GeminiRequest.java
  src/main/java/com/sparta/project/delivery/ai/dto/GeminiResponse.java
  src/main/java/com/sparta/project/delivery/ai/repository/AiRepository.java
  src/main/java/com/sparta/project/delivery/ai/service/GeminiService.java
  src/main/java/com/sparta/project/delivery/category/controller/CategoryController.java
  src/main/java/com/sparta/project/delivery/category/dto/CategoryDto.java
  src/main/java/com/sparta/project/delivery/category/dto/CategoryRequest.java
  src/main/java/com/sparta/project/delivery/category/dto/CategoryResponse.java
  src/main/java/com/sparta/project/delivery/category/entity/Category.java
  src/main/java/com/sparta/project/delivery/category/repository/CategoryRepository.java
  src/main/java/com/sparta/project/delivery/category/service/CategoryService.java
  src/main/java/com/sparta/project/delivery/common/exception/DeliveryError.java
  src/main/java/com/sparta/project/delivery/menu/controller/MenuController.java
  src/main/java/com/sparta/project/delivery/order/controller/OrderController.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderDto.java
  src/main/java/com/sparta/project/delivery/order/dto/OrderRequest.java
  src/main/java/com/sparta/project/delivery/order/repository/OrderRepository.java
  src/main/java/com/sparta/project/delivery/order/service/OrderService.java
  src/main/java/com/sparta/project/delivery/region/controller/RegionController.java
  src/main/java/com/sparta/project/delivery/region/dto/RegionDto.java
  src/main/java/com/sparta/project/delivery/region/dto/RegionRequest.java
  src/main/java/com/sparta/project/delivery/region/dto/RegionResponse.java
  src/main/java/com/sparta/project/delivery/region/entity/Region.java
  src/main/java/com/sparta/project/delivery/region/repository/RegionRepository.java
  src/main/java/com/sparta/project/delivery/region/service/RegionService.java
  src/main/java/com/sparta/project/delivery/review/controller/ReviewController.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewDto.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewReportDto.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewReportRequest.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewRequest.java
  src/main/java/com/sparta/project/delivery/review/dto/ReviewResponse.java
  src/main/java/com/sparta/project/delivery/review/entity/Review.java
  src/main/java/com/sparta/project/delivery/review/repository/ReviewRepository.java
  src/main/java/com/sparta/project/delivery/review/service/ReviewService.java
  src/main/java/com/sparta/project/delivery/store/repository/StoreRepository.java
  src/main/java/com/sparta/project/delivery/user/repository/UserRepository.java
Labels: enhancement

#69 Fix : Menu API 수정 - 유저 권한 검증, 데이터 유효성 검증, swagger
  src/main/java/com/sparta/project/delivery/inquiry/controller/InquiryController.java
  src/main/java/com/sparta/project/delivery/menu/constant/MenuSearchType.java
  src/main/java/com/sparta/project/delivery/menu/controller/MenuController.java
  src/main/java/com/sparta/project/delivery/menu/dto/request/CreateMenu.java
  src/main/java/com/sparta/project/delivery/menu/dto/request/UpdateMenu.java
  src/main/java/com/sparta/project/delivery/menu/entity/Menu.java
  src/main/java/com/sparta/project/delivery/menu/repository/MenuRepository.java
  src/main/java/com/sparta/project/delivery/menu/service/MenuService.java
  src/main/java/com/sparta/project/delivery/notice/controller/NoticeController.java
Labels: enhancement

#71 Fix : 에러 타입 별 status 수정, 서비스 코드 리팩토링
  src/main/java/com/sparta/project/delivery/common/exception/DeliveryError.java
  src/main/java/com/sparta/project/delivery/inquiry/service/InquiryService.java
  src/main/java/com/sparta/project/delivery/menu/service/MenuService.java
  src/main/java/com/sparta/project/delivery/notice/controller/NoticeController.java
  src/main/java/com/sparta/project/delivery/notice/service/NoticeService.java
Labels: enhancement
